# Generated by Django 2.2.4 on 2020-09-04 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='years_collecting',
            new_name='number_of_cards_owned',
        ),
    ]
