# Generated by Django 2.2.4 on 2020-09-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_card_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='release_date',
            field=models.DateField(default='2020-04-14'),
        ),
    ]
