# Generated by Django 2.2.4 on 2020-09-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200906_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
